# if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
domain: manikandan.github.io       
# the base hostname and protocol for your site, e.g. http://example.com
url: "https://manikandan.github.io"
# place folder name if the site is served in a subfolder
baseurl: "/blog-using-jekyll"
ignore_theme_config: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag